<a href="https://colab.research.google.com/github/ieg-dhr/DigiKAR/blob/main/JupyterNotebooks_DigiKAR/Factoids_Step0_CompareEntities.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This is a script to compare the content of factoid lists in AP3.

In [1]:
## mount drive
from google.colab import drive
drive.mount("/content/drive")
directory="/content/drive/My Drive/Colab_DigiKAR/"

Mounted at /content/drive

In the second step, we have to install additional Packages needed for working with CSV, EXCEL and DataFrames.

In [2]:
## install packages that are not part of Python's standard distribution

!pip install xlsxwriter
!pip install pandas
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting xlsxwriter
  Downloading XlsxWriter-3.0.9-py3-none-any.whl (152 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 152.8/152.8 KB 4.5 MB/s eta 0:00:00
Installing collected packages: xlsxwriter
Successfully installed xlsxwriter-3.0.9
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandas in /usr/local/lib/python3.9/dist-packages (1.4.4)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.9/dist-packages (from pandas) (2022.7.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.9/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.9/dist-packages (from pandas) (1.22.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: numpy in /usr/local/lib/python3.9/dist-packages (1.22.4)

We can now import the packages to the script and load our data. Not all packages imported here will be needed for all (optional) sections of the code.

In [13]:
import xlsxwriter
import csv
import pandas as pd
from pandas import DataFrame
import numpy as np
import os
import re

# path to input files

factoid_path_Profs="https://github.com/ieg-dhr/DigiKAR/blob/main/Sample%20Data/Factoid_PROFS_consolidation_STEP2_events-reconstructed.xlsx?raw=true"
factoid_path_Jahns="https://github.com/ieg-dhr/DigiKAR/blob/main/Sample%20Data/FactoidList_Erfassung_Jahns_Master_2023-02-22-Kopie.xlsx?raw=true"
factoid_path_Erfurt="https://github.com/ieg-dhr/DigiKAR/blob/main/Sample%20Data/FactoidList_Erfassung_Erfurt_Master_2022-11-11_Kopie.xlsx?raw=true" 
factoid_path_Staatskalender0="https://github.com/ieg-dhr/DigiKAR/blob/main/Sample%20Data/FactoidList_1756er_Staatskalender_Meta_final_TEST-MB_FS0.xlsx?raw=true"
factoid_path_Staatskalender1="https://github.com/ieg-dhr/DigiKAR/blob/main/Sample%20Data/FactoidList_1756er_Staatskalender_Meta_final_TEST-MB_FS1.xlsx?raw=true"
factoid_path_Staatskalender2="https://github.com/ieg-dhr/DigiKAR/blob/main/Sample%20Data/FactoidList_1756er_Staatskalender_Meta_final_TEST-MB_FS2.xlsx?raw=true"
factoid_path_Staatskalender3="https://github.com/ieg-dhr/DigiKAR/blob/main/Sample%20Data/FactoidList_1756er_Staatskalender_Meta_final_TEST-MB_FS3.xlsx?raw=true"
factoid_path_Staatskalender4="https://github.com/ieg-dhr/DigiKAR/blob/main/Sample%20Data/FactoidList_1756er_Staatskalender_Meta_final_TEST-MB_FS4.xlsx?raw=true"
factoid_path_Staatskalender_Extrakt="https://github.com/ieg-dhr/DigiKAR/blob/main/Sample%20Data/FactoidList_gesamt_Staatskalender_Meta_final_Python_Extrakt_GITHUB.xlsx?raw=true"
person_names_data2023="https://github.com/ieg-dhr/DigiKAR/blob/main/Sample%20Data/Factoid_PersonNames_Data2023.xlsx?raw=true"
person_names_general="https://github.com/ieg-dhr/DigiKAR/blob/main/Sample%20Data/Factoid_PersonNames_Gesamtauswertung.xlsx?raw=true"

factoid_paths=[person_names_general, person_names_data2023] # change selected files if needed

Run **THIS** section of code if you are comparing ontology lists such as person name lists from DigiKAR project. The column names of these files are different from the standard factoid template defined for the project.

In [14]:
# read only selected cells from different input files
# adjust the code below depending on column names in your input data
# example for comparing person names from different EXCEL tables

df_2023 = pd.read_excel(person_names_data2023, index_col=None, dtype=str)
df_2023 = df_2023.fillna("n/a") # replace empty fields for string

df_general = pd.read_excel(person_names_general, index_col=None, dtype=str)
df_general = df_general.fillna("n/a") # replace empty fields for string

df_merged = df_2023.merge(df_general)
display(df_merged)

# combine dataframes on shared columns

workbook=directory+'FACTOIDS_consolidated/Factoid_PersonNames_merged.xlsx'
print(workbook)
writer = pd.ExcelWriter(workbook, engine='xlsxwriter') # create a Pandas Excel writer using XlsxWriter as the engine.
df_merged.to_excel(writer, sheet_name='PersMerged') # Convert the dataframe to an XlsxWriter Excel object.
writer.save() # Close the Pandas Excel writer and output the Excel file.
print("Done.")

,Unnamed: 0,pers_ID,pers_name,alternative_names,Unnamed: 4,id,name_new_fs,ID_fs,poi,pers_name_corr,freq
0,31746,3,[Adolph Freiherr] von Bellmont,n/a,n/a,2,Adolph von Bellmont,3,poi-1,[Adolph Freiherr] von Bellmont,1
1,31588,48,[Andreas Ignaz] Meyer,n/a,n/a,3,Andreas Ignaz Meyer,48,0,[Andreas Ignaz] Meyer,1
2,31870,51,[Anselm Franz] Molitoris,n/a,Verwandtschaft mit 52: ggf. über rel_pers ausl...,4,Anselm Franz Molitoris,51,poi-1,[Anselm Franz] Molitoris,9
3,32255,51,[Anselm Franz] Molitoris,Molitor,n/a,4,Anselm Franz Molitoris,51,poi-1,[Anselm Franz] Molitoris,9
4,31881,84,[Christoph Ignaz] Streit,Streit Junior,n/a,5,Christoph Ignaz Streit,84,poi-1,[Christoph Ignaz] Streit,3
...,...,...,...,...,...,...,...,...,...,...,...
1368,31826,82,Wilhelm Moritz Strecker,n/a,n/a,1236,Wilhelm Moritz Strecker,82,poi-2,Wilhelm Moritz Strecker,10
1369,37638,n/a,Wilhelm Moritz Strecker,n/a,n/a,1236,Wilhelm Moritz Strecker,82,poi-2,Wilhelm Moritz Strecker,10
1370,32807,285,Wilhelm Streit,n/a,n/a,1237,0,285,0,Wilhelm Streit,6
1371,35974,561,Wolf Balthasar von der Weser,n/a,n/a,1238,Wolf Balthasar von der Weser,561,poi-2,Wolf Balthasar von der Weser,5
1372,32196,213,Wolff Christoph von Ziegler,n/a,n/a,1239,0,213,0,Wolff Christoph von Ziegler,1

/content/drive/My Drive/Colab_DigiKAR/FACTOIDS_consolidated/Factoid_PersonNames_merged.xlsx
Done.

Run **THIS** section of the code if you are comparing Factoid lists cotaining all required columns (see below)!

In [ ]:

# structure of fully-formed factoid input files

column_names = ["factoid_ID",
                "pers_ID",
                "alternative_names",
                "event_type",
                "event_after-date",
                "event_before-date",
                "event_start",
                "event_end",
                "event_date",
                "pers_title",
                "pers_function",
                "place_name",
                "inst_name",
                "rel_pers",
                "source_quotations",
                "additional_info",
                "comment",
                "info_dump",
                "source",
                "source_site"]

# lists to store selected data                
                
pers_name_list=[]
pers_ID_list=[]
pers_alt_list=[]

# read all factoid files from file paths to dataframe

for file in factoid_paths:
    df = pd.read_excel(file, index_col=None, dtype=str) # axis=1, sort=False sheet_name='FactoidList'
    df = df.fillna("n/a") # replace empty fields for string
    df_length=len(df)
    
    try:
      for x in range(0, df_length):
          pers_list=[]
          pers_count=(df_length - x)
          e_df=df.iloc[[x]].fillna("n/a") # virtual value to avoid issues with empty data frames
          pers_name=e_df['pers_name'].values[0]
          try: 
              pers_ID=e_df['pers_ID'].values[0]
          except KeyError:
              pers_ID="n/a"

          try:
              alt_names=e_df['alternative_names'].values[0]
          except KeyError:
              pers_ID="n/a"

          pers_name_list.append(pers_ID)
          pers_ID_list.append(pers_name)
          pers_alt_list.append(alt_names)

    except IndexError:
      print("No more names found.")

df_pers = pd.DataFrame(zip(*[pers_name_list, pers_ID_list, pers_alt_list]))

# count overall number of person names in the data

print("There are ", len(df_pers), "person names in your DataFrame!")

# delete all duplicate rows with exact matches

f_unique=df_pers.drop_duplicates()
print("Your DataFrame has now ", len(f_unique), "unique names (including alternative names).")

display(f_unique)

# write list of all unique names found to a new file

workbook=directory+'FACTOIDS_consolidated/Factoid_all_names.xlsx'
print(workbook)
writer = pd.ExcelWriter(workbook, engine='xlsxwriter') # create a Pandas Excel writer using XlsxWriter as the engine.
f_unique.to_excel(writer, sheet_name='all_names') # Convert the dataframe to an XlsxWriter Excel object.
writer.save() # Close the Pandas Excel writer and output the Excel file.
print("Done.")

Check the output files and repeat process if necessary.

Script by Monika Barget, Maastricht/Mainz

January 2023